# Generated by Django 3.2.23 on 2024-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_orderdetails_orderheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='cart',
            field=models.ManyToManyField(to='core.Cart'),
        ),
    ]
